apiVersion: core.spinoperator.dev/v1alpha1
kind: SpinApp
metadata:
  name: simple-spinapp-scaled
spec:
  image: "ghcr.io/megamxl/post:v1"
  replicas: 1
  executor: containerd-shim-spin
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 400Mi

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: simple-spinapp-scaled
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50