spin_manifest_version = 2

[application]
name = "benchmarking"
version = "0.1.0"
authors = ["mopedmaxl"]
description = "Bench It"

[[trigger.http]]
route = "/factor/..."
component = "factor"

[component.factor]
source = "factor.wasm"
allowed_outbound_hosts = []
[component.factor.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o factor.wasm factor-func/factor.go"
watch = ["**/*.go", "go.mod"]


[[trigger.http]]
route = "/matrix/..."
component = "matrix"

[component.matrix]
source = "matrix.wasm"
allowed_outbound_hosts = []
[component.matrix.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o matrix.wasm matrix-func/matrix.go"
watch = ["**/*.go", "go.mod"]

[[trigger.http]]
route = "/latency/..."
component = "latency"

[component.latency]
source = "latency.wasm"
allowed_outbound_hosts = []
[component.latency.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o latency.wasm latency-func/latency.go"
watch = ["**/*.go", "go.mod"]

