spin_manifest_version = 2

[application]
name = "customerReducer"
version = "0.1.0"
authors = ["mopedmaxl <maxl@maxl.at>"]
description = ""

[[trigger.http]]
route = "/..."
component = "customer-reducer"

[component.customer-reducer]
source = "main.wasm"
allowed_outbound_hosts = ["http://192.168.178.250:8085"]
[component.customer-reducer.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
watch = ["**/*.go", "go.mod"]
