apiVersion: core.spinoperator.dev/v1alpha1
kind: SpinApp
metadata:
  name: benchmark-spin
spec:
  image: "ghcr.io/megamxl/benchmarking:v1"
  replicas: 10
  executor: containerd-shim-spin

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: benchmark-spin
                port:
                  number: 80